# version 2
dist: xenial
sudo: false

branches:
  only:
    - master
    - stable

language: node_js
cache: npm
node_js: 10

install:
  - pip install --user -r requirements.txt
  - npm install
  - 'if [[ "$TRAVIS_BRANCH" = stable ]]; then npm install kaitai-struct-compiler@latest && npm install kaitai-struct@latest && node vendor_build.js; fi'

script:
  - '[ "$TRAVIS_BRANCH" = stable ] && export GA_ID=UA-76299550-2 || export GA_ID=UA-76299550-3'
  - '[ "$TRAVIS_BRANCH" = stable ] && export SENTRY_ENV=stable || export SENTRY_ENV=devel'
  - 'export SENTRY_DSN=https://a01cdb58ab3e43dd9ce695dd20a19d00@sentry.io/202888'
  - ./build

after_success:
  - ./push_artifacts/git_config_kaitai_bot
  - ./push_artifacts/publish
      -o kaitai-io
      -r ide-kaitai-io.github.io
      -d "$([ "$TRAVIS_BRANCH" != stable ] && echo devel)"
      -m "Regen $TRAVIS_BRANCH kaitai-io/kaitai_struct_webide@$TRAVIS_COMMIT"
      --
      --exclude=.git
      --exclude=CNAME
      --exclude=.nojekyll
      --exclude=devel
      out/
